Add files via upload
Seagate/Lyve-Cloud-Solutions-Samples pull request #52
Opened 2022-09-01 19:29 UTC by AkulkarniStx

This is Tar Indexing and Extract tool. Small files can be tarred to get faster upload times and then extraction using index created while uploading lets one pull exactly whats needed from the tar.

## Integration title

### Integration details

### How Has This Been Tested?

### Screenshots

### Checklist
- [ ] I've signed my commits (git commit -s)
- [ ] Code was tested locally
- [ ] Installation instructions are provided

I contribute this code under Apache License 2.0

2022-09-14 16:21 UTC, barviv-seagate commented on tar-index-extract/README.md
> +* August 22, 2021: Bari Arviv (bari.arviv@seagate.com) on Ubuntu 20.4
@AkulkarniStx please change it to your name. email and OS

2022-09-15 09:33 UTC, sasha-seagate submitted a review, later dismissed

2022-09-25 09:19 UTC, sasha-seagate submitted a review, later dismissed

2022-09-25 10:43 UTC, leon-seagate requested changes
Hey Arati,
the program runs, yet some instruction in the README are missing/unclear :
please add 'requirements' file for lib's to be installed,  change 'indexing file' section to detailed example script  in bash a.k.a 
bash
```
python3 <Tool directory> --tarfile <index file location>
```
please change 'sample output' section to detailed script a.k.a:
```
python3 <tool location>
--extract <tarfile.tar absolute path><all full file names parted by columns without any spaces !!!!
--outputpath <output path>
--bucket <Bucket name>
```
also add 
## Tested by
* Sep 25, 2022: Leon Markovich (leon.markovich@seagate) on Ubuntu 20.04.3 LTS
* Sep 18, 2022: Sasha Chernin(alexander.chernin@seagate) on Windows 10
* Sept 04, 2022: Arati Kulkarni (arati.kulkarni@seagate.com) on Windows 10
*

2022-09-29 07:44 UTC, sasha-seagate approved these changes

2022-09-29 07:44 UTC, leon-seagate approved these changes

2022-09-29 07:52 UTC, merged